better inputs and outputs

diff --git a/.github/workflows/rawls-run-azure-e2e-tests.yaml b/.github/workflows/rawls-run-azure-e2e-tests.yaml
--- a/.github/workflows/rawls-run-azure-e2e-tests.yaml
+++ b/.github/workflows/rawls-run-azure-e2e-tests.yaml
@@ -22,15 +22,21 @@ env:
   TOKEN: '${{ secrets.BROADBOT_TOKEN }}' # github token for access to kick off a job in the private repo
 
 jobs:
-  workflow-inputs:
+  init-github-context:
     runs-on: ubuntu-latest
     outputs:
-      branch: ${{ inputs.branch || 'develop' }}
-      delete-bee: ${{ inputs.delete-bee || true }}
+      branch: ${{ steps.extract-inputs.outputs.branch }}
+      delete-bee: ${{ steps.extract-inputs.outputs.delete-bee }}
+    steps:
+      - name: Get inputs or use defaults
+        id: extract-inputs
+        run: |
+          echo "branch=${{ inputs.branch || 'develop' }}" >> "$GITHUB_OUTPUT"
+          echo "delete-bee=${{ inputs.delete-bee || true }}" >> "$GITHUB_OUTPUT"
 
   rawls-build-tag-publish-job:
     runs-on: ubuntu-latest
-    needs: [workflow-inputs]
+    needs: [init-github-context]
     permissions:
       contents: 'read'
       id-token: 'write'
@@ -55,7 +61,7 @@ jobs:
           repo: broadinstitute/terra-github-workflows
           ref: refs/heads/main
           token: ${{ env.TOKEN }}
-          inputs: '{ "repository": "${{ github.event.repository.full_name }}", "ref": "refs/heads/${{ needs.workflow-inputs.branch }}", "rawls-release-tag": "${{ steps.tag.outputs.tag }}" }'
+          inputs: '{ "repository": "${{ github.event.repository.full_name }}", "ref": "refs/heads/${{ needs.init-github-context.outputs.branch }}", "rawls-release-tag": "${{ steps.tag.outputs.tag }}" }'
 
       - name: Render Rawls version
         id: render-rawls-version
@@ -87,7 +93,7 @@ jobs:
 
   rawls-swat-e2e-test-job:
     runs-on: ubuntu-latest
-    needs: [create-bee-workflow, workflow-inputs]
+    needs: [create-bee-workflow, init-github-context]
     permissions:
       contents: 'read'
       id-token: 'write'
@@ -101,12 +107,12 @@ jobs:
           repo: broadinstitute/terra-github-workflows
           ref: refs/heads/main
           token: ${{ env.TOKEN }}
-          inputs: '{ "bee-name": "${{ env.BEE_NAME }}", "ENV": "qa", "ref": "refs/heads/${{ needs.workflow-inputs.branch }}", "test-group-name": "workspaces_azure", "test-command": "${{ env.rawls_test_command }}", "java-version": "17" }'
+          inputs: '{ "bee-name": "${{ env.BEE_NAME }}", "ENV": "qa", "ref": "refs/heads/${{ needs.init-github-context.outputs.branch }}", "test-group-name": "workspaces_azure", "test-command": "${{ env.rawls_test_command }}", "java-version": "17" }'
 
   destroy-bee-workflow:
     runs-on: ubuntu-latest
-    needs: [rawls-swat-e2e-test-job, workflow-inputs]
-    if: ${{ needs.workflow-inputs.delete-bee && always() }} # always run to confirm bee is destroyed unless explicitly requested not to
+    needs: [rawls-swat-e2e-test-job, init-github-context]
+    if: ${{ needs.init-github-context.outputs.delete-bee && always() }} # always run to confirm bee is destroyed unless explicitly requested not to
     permissions:
       contents: 'read'
       id-token: 'write'
@@ -122,7 +128,7 @@ jobs:
 
   notify-slack-on-failure:
     runs-on: ubuntu-latest
-    needs: [workflow-inputs, rawls-build-tag-publish-job, create-bee-workflow, rawls-swat-e2e-test-job, destroy-bee-workflow] # Want to notify regardless of which step fails
+    needs: [init-github-context, rawls-build-tag-publish-job, create-bee-workflow, rawls-swat-e2e-test-job, destroy-bee-workflow] # Want to notify regardless of which step fails
     if: ${{ failure() }}
     steps:
       - name: Notify slack
